# Generated by Django 4.2.23 on 2025-06-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
